Styling
icmutualaid/icma-website pull request #8
Opened 2024-03-26 18:48 UTC by junkshark8

Styled nav and made it responsive, styled pages and added some buttons & icons for usability, created footer with social/email links

2024-03-26 20:01 UTC, ada-fruit requested changes

2024-03-26 20:01 UTC, ada-fruit commented on .DS_Store
yucky, i'll add these to `.gitignore`

2024-03-26 20:07 UTC, ada-fruit commented
also: Closes #3

2024-03-26 20:35 UTC, ada-fruit commented
actions plz

2024-03-26 21:55 UTC, ada-fruit commented on blog/static/favicon.ico
also, what is this diff? i'm assuming you just fixed the dimensions? (i made the old favicon in like 5 minutes, so i would not be offended if you wanted to replace it)

2024-03-28 13:40 UTC, junkshark8 commented on blog/static/favicon.ico
It had a transparent bg and looked weird in my browser

2024-03-28 14:32 UTC, junkshark8 commented on blog/static/colors.css
> +:root {
gonna do [this](https://stackoverflow.com/questions/50910404/best-practice-for-naming-css-color-variables#:~:text=Or%20by%20their%20meaning%2Ffunction,%2C%20disabled%2Dcolor%20...&text=meaning%2Ffunction%20is%20the%20best,and%20changes%20on%20a%20site.)

2024-03-28 19:00 UTC, ada-fruit commented on blog/static/colors.css
> +:root {
even better, thanks for the research

2024-03-28 19:14 UTC, ada-fruit requested changes

2024-03-28 19:14 UTC, ada-fruit commented on blog/templates/base.html
> +        <a class="logo" href="" aria-label="Home">
should be `href="/"` to point to the main page

2024-03-28 19:24 UTC, ada-fruit approved these changes

2024-03-28 19:25 UTC, merged